- topsort-catalog-service.yaml
API clients get weird when you pass query params with spaces in them, and that can cause compatibility problems.
For example `this is a string` will converted to `this+is+a+string`
> Update next and prev requirements

- topsort-catalog-service.yml
We avoid having anonymous schemas as otherwise they are not able to be used by generated code.
We also simplify the names removing common prefixes and suffixes.
> chore: improve catalog types and names

- topsort-catalog-service.yml
- Remove `prev` from the documentation
- Reuse the param, so that the same explanation is used for all endpoints
- Reword the documentation
> chore: improve pagination documentation 

- topsort-catalog-service.yml
`price` and `stock` were defined as number but they are indeed integers.
> chore: use integer type

- topsort-catalog-service.yml
This field was not being used by the Catalog Service.
> chore: remove logoURL from vendor

- topsort-catalog-service.yml
The actual response is an array, not wrraped in an object.
We also make required the name of the product, which is required by the catalog service.
> fix: getProductsById response

- topsort-catalog-service.yml
The brand was not being used so we remove it for now to simplify the integration.
> chore: remove brand from the product response

- topsort-catalog-service.yml
- topsort-endpoints.yml
We use the workaround described in https://github.com/Redocly/redoc/issues/134 to display the models as an API section. We also fix a typo, a documentation reference and remove a redundant comment.
> chore: add models section

- topsort-api-v2.yml
- Address some comments from @sk- in https://github.com/Topsort/openapi/pull/35:
- Remove events.
- Remove `Ads` from the component names.
- Fix typo.
- Describe what a usable bid is.
- Rename response fields to avoid repeating `winner`.
- Remove `quality`.
- Add description for `slotId`.
- Update servers.
- Relax `anyOf` restriction; while valid according to the OpenAPI spec, this causes issues with Redoc.ly — Other solutions such as Rapidoc or Swagger don't have such issues.
> fix: v2 comments

- topsort-api-v1.yml
- topsort-api-v2.yml
This was breaking requests from the `Try me!` sections.
> fix: use structurally valid resolvedBidId in examples

- topsort-api-v2.yml
- Use aspect ratio instead of an ID to reference banner groups.
- Comment out searchQuery until we support it.
- Remove geoTargeting from banners.
> chore: use aspectRatio, remove searchQuery, geoTargeting from banner ads

- topsort-api-v1.yml
Remove some useless (from the point of view of an external dev) auction request models to declutter the list of models.
> chore(v1): remove redundant models

- topsort-api-v2.yml
The hack to display models in Redocly (with a `SchemaDefinition` JSX injection) does not work with multiple options, so any dropdowns based on discriminators are broken; this change hides that broken entry from the list of models.
> chore(v2): remove AuctionRequest from All Models section

- topsort-api-v1.yml
The manager no longer has views for banners v1 and there are no remaining (meaning "non-deleted") v1 bids in any production environment (this includes demo and sandbox). We will no longer support this API and will remove it from the docs to avoid confusion with v2.
> chore: remove banners from v1 documentation

- topsort-api-v2.yml
Update schema according to the changes in https://github.com/Topsort/auction-engine/pull/1358. As far as we know, no one is using this yet.
> fix: use camel case in JSON body

- topsort-api-v2.yml
Schema:
- [v2/events] forbid any additional properties for events v2 request schema.
- [v2/events] change `purchaseItems`' unit price format to the 64-bit precision `double`.
Docs:
- [v2] add an API description.
- [v2] fix server URL.
- [v2/auctions] fix response example to match the request cardinality.
- [v2/events] add request example.
> chore: forbid additional properties for events v2

- topsort-api-v2.yml
Change `category` fields for sponsored listings so that multiple (conjunctive) categories may be provided at once.
- Updates the (commented out) category field in auctions v2.
- Updates the placement field in events v2.
> chore: allow multiple categories in API v2

- topsort-api-v2.yml
Document new `slotId` as implemented by https://github.com/Topsort/auction-engine/pull/1555.
> chore: use slot IDs for banner ads instead of aspect ratios

- topsort-api-v2.yml
The documentation model for category disjunctions doesn't match what we have on the auction engine. This PR fixes that.
> Chore: Fix disjunctions

- .github/workflows/readme-v2-auctions.yml
- topsort-api-v1.yml
- topsort-api-v2.yml
To avoid further problems, we added fake endpoints, so we don't move every page from the ReadMe generated category. Moving every page is the cause of breakage.
> Fix ReadMe Integration.

- topsort-api-v1.yml
These endpoints have been replace by version 2 for a couple years now, and have been described as depreacted in the Readme Docs. See https://docs.topsort.com/reference/events and https://docs.topsort.com/reference/auctions.
> chore: mark v1 endpoints as deprecated

- topsort-api-v2.yml
Adds the optional vendor id definition for purchases to our docs
> docs: add vendor id definition for purchases

- topsort-api-v2.yml
This PR adds the `campaignId` as part of `/v2/auctions` winners example
> chore: add campaign id to v2 winner example

- topsort-api-v2.yml
Add recommendation for maximum amount of products to send on an auction.
This will not be enforced on engine (that's why it is a recommendation), but we will start introducing some limits.
> chore: add recommendation for max products in auction

- topsort-api-v2.yml
This PR updates the /v2/auctions/sponsored-brand endpoint.
Key Changes:
Endpoint Enhancements:
- Revised request and response schemas.
Improved Documentation:
- Expanded property descriptions.
- Included comprehensive request/response examples.
> chore: improve sponsored brands examples

- topsort-api-v2.yml
Add travel auction open api documentation to v2
> chore: add travel auction to v2

- topsort-api-v2.yml
Noticed that the auction and event post documentations where missing descriptions
> chore: refactor events description

- topsort-api-v2.yml
Redo of https://github.com/Topsort/openapi/pull/136
> chore: refactor opaque user id

- .github/workflows/check-specs.yml
- topsort-api-v2.yml
First version of toptimize ranking endpoint
> chore(toptimize): First version ranking endpoint

- topsort-api-v2.yml
Returning vendorId is already supported
opaqueUserId is currently a no-op but will be needed for segments.
> chore: added opaqueUserId and vendorId as optionals for Sponsored Brands auctions

- topsort-api-v2.yml
jira ticket https://topsort.atlassian.net/jira/software/projects/INTE/boards/21?assignee=712020%3Abfdce163-008e-49fc-8c99-27501fc7d3b1&selectedIssue=INTE-1516
We add a use case in the report events documentation where a user can track different sections of the same page using the placement object, which they can later differentiate via the Data Room for analytics.
Swagger UI render:
> docs: add placement tracking example for carousel analytics

- topsort-api-v2.yml
Update v2/events API docs with new changes: 
- Pageview event
- Page struct
- externalCampaignID and externalVendorID fields
- clickType field for sponsored events
- Object struct for non sponsored events
Closes: https://topsort.atlassian.net/browse/AE-148
> chore: update events endpoint to reflect api

- topsort-api-v2.yml
We missed the references to display the new pageview event on the previous PR.
> chore: add missing references to display new pageview object

- topsort-api-v2.yml
* Change the prefix of the forecasting endpoints from `/toptimize/v1` to `/public/v1/toptimize`
This change was required because of issues in the deployment of the public endpoint.
> fix(forecasting): change forecasting endpoint prefix

- topsort-api-v2.yml
By using multiple responses, Mintlify hides any example but the first. This is not helpful.
> chore(v2/auctions): use one example array

- topsort-api-v2.yml
Updated sponsored brands documentation to match v2.
Tried `oneOf` in line 1420. Doesn't work in the editors render, but I wonder if it works in mintilfy. The idea is that we show three different scenarios for the three different triggers. This is to avoid showing all three and creating confusions (you can only use one at the time).
> feat: update v2 sponsored brands

- topsort-api-v2.yml
In reality our API can take empty arrays, but at least one of them must be non-empty
> fix: events minintems
