Topsort/openapi

- topsort-endpoints.yml
relates to https://github.com/Topsort/auction-engine/pull/596
> [TPS-1353] - add occurred at field

- topsort-endpoints.yml
- remove wrong fields (currency, id)
- add correct response
- bring back some descriptions from gitbook (https://topsort.gitbook.io/topsort-integration/e-comm-int/impressions).
> chore: events fixes 

- topsort-catalog-service.yaml
- Simplified the summary so that it looks good on our documentation sites
- Removed spanish words
- Added tags for the Health Ceheck endpoint
> chore: catalog improvements

- topsort-catalog-service.yaml
According to Pancho, we have only communicated to our customers that the limit is 50.
> chore: fix array limits

- topsort-catalog-service.yml
- For most strings require a minimum length of 1
- For ints require an int32
- Add array constraints to product response
- Remove 404 response
> chore: add type formats and improvements

- topsort-catalog-service.yml
The response was incorrectly marked as being paginated.
> fix: getProductById response

- topsort-endpoints.yml
Based on:
- [Events API Improvements#Session](https://docs.google.com/document/d/1CJoqfqMxRkdL_0PMlKUWj8UchEeWbsI3PV3QAuxSpys/edit#heading=h.fikdp73w1wjy)
- [Session ID Action Items#Simplify Events Endpoints](https://docs.google.com/document/d/1uoDri6yp8HGtLAk_Sg265MIq-oMCRZrSAqoZcHakFik/edit#heading=h.w1irafipqfal).
> chore: update Session schema

- topsort-endpoints.yml
Fix events type order. Add missing point.
> fix: show impressions as the default event

- topsort-api-v1.yml
- topsort-api-v2.yml
Check in https://editor.swagger.io/
> feat: add Topsort API v2

- topsort-api-v1.yml
Remove sessionID requirement on auction endpoint
> [IP-288] - remove session from auction endpoint

- topsort-api-v1.yml
Add missing fields to v1 examples.
> fix: add missing fields to v1 examples

- topsort-api-v2.yml
- Do not display base AuctionRequest definition.
- Make `products` required for sponsored listings (and length at least one).
- Fix auction request example.
- Add missing descriptions.
> chore: improve documentation

- topsort-api-v1.yml
Simplify models, ensure schemas render correctly in Redocly.
> fix(v1): event requests

- topsort-api-v1.yml
- topsort-api-v2.yml
This PR is part of a series of changes related to our error codes:
- https://github.com/Topsort/auction-engine/pull/1019
- https://docs.topsort.com/reference/errors (updated) ✅
> fix: update TopsortError model, rename to Error

- catalog-crud-api.yml
> fix: add pagination params to "get many" endpoints

- catalog-crud-api.yml
- Include IDs in upsert bodies.
- Rename `vendorIds`/`categoryIds` fields to `vendors`/`categories`.
- Add missing `brand` field.
- Add server path, fix routes.
> fix(crud API): various fixes

- topsort-api-v2.yml
[Events V2 preview](https://preview.redoc.ly/topsort-api/fix%2Fchange-events-v2-docs/v2#tag/Events-(Beta)).
> fix: change PLP to PDP, add beta notice

- topsort-api-v1.yml
- topsort-api-v2.yml
These checks are already enforced in the actual handlers. This is just a documentation update.
> chore: reject empty strings

- topsort-api-v2.yml
https://topsort.atlassian.net/browse/INTG-2505
> chore(opaqueUserId): update description

- topsort-api-v2.yml
https://topsort.atlassian.net/browse/INTG-2523?atlOrigin=eyJpIjoiYzUzODllMDE0MWQyNDA1ZmE5NjlhZjFmYTZlNGQ4ZjAiLCJwIjoiaiJ9
> fix(opaqueUserId): change months to at least a year

- topsort-api-v1.yml
- topsort-api-v2.yml
- topsort-catalog-service.yml
> switch to new logo

- topsort-api-v2.yml
Some changes on definitions on the API to make it more intuitive.
> changes on events documentation

- topsort-api-v1.yml
- topsort-api-v2.yml
We do not return that error code.
> chore: remove payment required status code

- topsort-api-v1.yml
- topsort-api-v2.yml
It was removed from the response in https://github.com/Topsort/openapi/pull/121
> chore: remove unused PaymentRequired component

- topsort-api-v2.yml
Add documentation for the endpoint v2/auctions/sponsored-brand
> add sponsored brand auction documentation

- topsort-api-v1.yml
- topsort-api-v2.yml
> chore: remove fake endpoint

- topsort-api-v2.yml
Use the main server url as base, then pass version through path.
> chore: change prefix for base url

- .github/workflows/validate-typos.yml
- .typos.toml
Help writers by finding typos in CI.
> chore: check typos in ci

- topsort-api-v2.yml
Our documentation doesn't cover this which is an unfortunate miss.
> chore: document that halo attribution also requires a vendorid

- topsort-api-v2.yml
> chore: add beta flag to toptimize

- topsort-api-v2.yml
change title on toptimize rank
> chore: change title on toptimize rank

- topsort-api-v2.yml
Added flights to travel docs and refactored docs to be more consistent.
[RFC doc](https://docs.google.com/document/d/1OOB9_bLKXWfmBRG1QDzCNEssC8Mz9-I0YVrD-6CxqRY/edit?tab=t.0#heading=h.wla1iw7wibpn)
[JIRA Ticket](https://topsort.atlassian.net/browse/AE-145?atlOrigin=eyJpIjoiMDgyYWIzMGUzMDg0NDQ4YTgyNzhlY2FhNDIxZjQyZGQiLCJwIjoiaiJ9)
> feat: add flights to travel docs

- topsort-api-v2.yml
@baltazar-topsort asked me to upload the offsite beta api docs, so I added these endpoints to api v2 file. I tested the visualization using [ReDoc](https://redocly.github.io/redoc/) and it works, but I'm not sure if everything is correct.
> offsite beta endpoints documentation

- topsort-api-v2.yml
A few invalid referenes here:
1. Using a `type: null` in `anyOf`
2. Passing a description to a referenced object
3. Passing an empty security context at path level
4. Remove invalid references
> fix: correct Offsite Ads API and enhance Travel Auctions API

- topsort-api-v2.yml
New page for toptimize predictions endpoint + some minor format fixes
> feat: add toptimize predictions endpoint

- topsort-api-v2.yml
Minor fixes: 
- Fix products in example
- Add descriptions
> fix(toptimize): fix toptimize/v1/predictions docs

- topsort-api-v2.yml
- Document toptimize retrieval endpoint
- Fix on response codes for predictions
> feat: toptimize retrieval endpoint

- topsort-api-v2.yml
- Fix deviceType definition
- Fix objectType definition
- Fix typo on description of the endpoint
> fix: fix typos and descriptions on retrieval endpoint

- topsort-api-v2.yml
Hide the Toptimize section in the meantime
> chore: hide toptimize endpoints

- topsort-api-v2.yml
This reverts commit 1be04e33e019cc68f56b3e6202a7f8f237e5329e.
> revert: remove toptimize endpoints

- topsort-api-v2.yml
Include documentation for forecasting endpoints in toptimize:
- GET /toptimize/v1/forecasting/marketplace
- POST /toptimize/v1/forecasting/inventory
- POST /toptimize/v1/forecasting/campaign
Endpoint request document: https://docs.google.com/document/d/1Ldgm6M2xM5ZAzs6ly9TWgYW0owYMCVRRCL5lzlkDIT4/edit?tab=t.0
> feat: inventory forecasting endpoints

- .github/CODEOWNERS
This would just be a sign-off of the internal processes coming up to this point, since development and planning is already done.
> chore: make sure the public api team approves any changes

- topsort-api-v2.yml
Add existing `Page` object to auction request to match api
> chore: add `Page` object to auction request

- topsort-api-v2.yml
Update docs to reflect new fields on the api
> chore: add `page` field to sponsored brand request
